# Generated by Django 3.2 on 2021-05-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_User',
            fields=[
                ('first_name', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=70)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='My_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=500)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authenticationform.my_user')),
            ],
        ),
    ]
