# Generated by Django 3.2 on 2021-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_post',
            name='Text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
