# Generated by Django 3.2 on 2021-05-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationform', '0002_alter_my_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_post',
            name='Text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='my_post',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticationform.my_user'),
        ),
    ]
