# Generated by Django 3.2 on 2021-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationform', '0004_alter_my_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='password',
            field=models.IntegerField(max_length=60),
        ),
    ]
