# Generated by Django 3.2 on 2021-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('weight', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updates_at', models.DateField()),
            ],
        ),
    ]
