# Generated by Django 3.2 on 2021-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
