# Generated by Django 3.2 on 2021-05-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='price_in_rupees',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='weight',
            new_name='weight_in_grams',
        ),
    ]
